{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_allure.py:16: Exception"}, "start": 1731587037823, "stop": 1731587037823, "uuid": "810eac2d-b8cf-47c0-be88-084368de1349", "historyId": "cb41bd139e929d9eef92825c451cc27a", "testCaseId": "cb41bd139e929d9eef92825c451cc27a", "fullName": "test_allure#test_broken", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "孤独二里"}, {"name": "thread", "value": "21836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}