{"uid":"7e40ef0cfbc34b7a","name":"test_login_failure","fullName":"test_feature_story.TestLogin#test_login_failure","historyId":"a0fb827149424dbc77d431148fe9f888","time":{"start":1731589496592,"stop":1731589496592,"duration":0},"status":"failed","statusMessage":"AssertionError: assert '1' == 1","statusTrace":"self = <test_feature_story.TestLogin object at 0x0000022855E92CC0>\n\n    @allure.story(\"密码错误\")\n    def test_login_failure(self):\n        with allure.step(\"输入用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n    \n    \n    \n        with allure.step(\"登陆失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:23: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: assert '1' == 1","statusTrace":"self = <test_feature_story.TestLogin object at 0x0000022855E92CC0>\n\n    @allure.story(\"密码错误\")\n    def test_login_failure(self):\n        with allure.step(\"输入用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n    \n    \n    \n        with allure.step(\"登陆失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:23: AssertionError","steps":[{"name":"输入用户名","time":{"start":1731589496592,"stop":1731589496592,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false},{"name":"输入密码","time":{"start":1731589496592,"stop":1731589496592,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false},{"name":"登陆失败","time":{"start":1731589496592,"stop":1731589496592,"duration":0},"status":"failed","statusMessage":"AssertionError: assert '1' == 1\n","statusTrace":"  File \"D:\\PYPro\\Py_Td\\自动化测试框架\\test_feature_story.py\", line 23, in test_login_failure\n    assert '1' == 1\n","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true}],"attachments":[{"uid":"21c90a392d5c8fd3","name":"stdout","source":"21c90a392d5c8fd3.txt","type":"text/plain","size":42}],"parameters":[],"attachmentStep":false,"stepsCount":3,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"密码错误"},{"name":"feature","value":"登录"},{"name":"suite","value":"test_feature_story"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"孤独二里"},{"name":"thread","value":"28396-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_feature_story"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"7e40ef0cfbc34b7a.json","parameterValues":[]}